version: '3'

includes:
  redis:
    taskfile: ./redis/TaskFile.yaml
    dir: ./redis
  ssms:
    taskfile: ./ssms/TaskFile.yaml
    dir: ./ssms

tasks:
  start-all:
    cmds:
      - task: redis:redis-window
      - task: ssms:start-sql-server
    aliases:
      - start
    desc: "starts application"
